[package]
name = "skopio-zed"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]
members = ["skopio-ls"]

[workspace.package]
version = "0.1.0"

[dependencies]
zed_extension_api = "0.7.0"
